@PomodoroBackend.AOTApi_HostAddress = http://localhost:5196

GET {{PomodoroBackend.AOTApi_HostAddress}}/todos/
Accept: application/json

###

GET {{PomodoroBackend.AOTApi_HostAddress}}/todos/1
Accept: application/json

###
